import{createDeck,shuffleDeck}from"./deck";import{dealFive,DealResult,finishDeal}from"./deal";import{bid,startBidding,Bid,BiddingState}from"./bidding";import{currentWinner,legalCards,PlayedCard}from"./trick";import{cardPoints}from"./cards";import{addBolt,applyKaputPenalty,INITIAL_TARGET,nextTarget,winnerAtTarget}from"./scoring";import{Card,Seat,Suit,TeamId,TeamState}from"./types";import{settleRound}from"./round";
export type Phase="bidding"|"playing"|"round_end"|"game_over";
export interface GameState{phase:Phase;dealer:Seat;target:number;teams:Record<TeamId,TeamState>;deal:DealResult;bidding:BiddingState;hands?:Record<Seat,Card[]>;trump?:Suit;turn:Seat;trick:PlayedCard[];tricksWon:[number,number];capturedPoints:[number,number];declarations:[number,number];winner?:TeamId}
const next=(s:Seat)=>((s+1)%4)as Seat;export const teamOf=(s:Seat):0|1=>s%2===0?0:1;
export function newGame(random=Math.random):GameState{const dealer=Math.floor(random()*4)as Seat;return startRound(dealer,{A:{bil:0,bolts:0},B:{bil:0,bolts:0}},INITIAL_TARGET,random)}
function startRound(dealer:Seat,teams:Record<TeamId,TeamState>,target:number,random=Math.random):GameState{const deal=dealFive(shuffleDeck(createDeck(),random),dealer);return{phase:"bidding",dealer,target,teams,deal,bidding:startBidding(dealer,deal.faceUp.suit),turn:next(dealer),trick:[],tricksWon:[0,0],capturedPoints:[0,0],declarations:[0,0]}}
export function makeBid(g:GameState,seat:Seat,b:Bid):GameState{if(g.phase!=="bidding")throw Error("Not bidding");const bidding=bid(g.bidding,seat,b);if(!bidding.trump)return{...g,bidding,turn:bidding.turn};const hands=finishDeal(g.deal,g.dealer,bidding.taker!,bidding.trump);return{...g,phase:"playing",bidding,hands,trump:bidding.trump,turn:next(g.dealer)}}
export function setDeclarationPoints(g:GameState,team:0|1,points:number):GameState{if(g.phase!=="playing")throw Error("Not playing");const declarations=[...g.declarations]as[number,number];declarations[team]=points;return{...g,declarations}}
export function playCard(g:GameState,seat:Seat,card:Card):GameState{if(g.phase!=="playing"||!g.hands||!g.trump)throw Error("Not playing");if(seat!==g.turn)throw Error("Not your turn");const hand=g.hands[seat];const idx=hand.findIndex(c=>c.suit===card.suit&&c.rank===card.rank);if(idx<0)throw Error("Card not in hand");const legal=legalCards(hand,g.trick,g.trump);if(!legal.some(c=>c.suit===card.suit&&c.rank===card.rank))throw Error("Illegal card");const hands={...g.hands,[seat]:hand.filter((_,i)=>i!==idx)};const trick=[...g.trick,{seat,card}];if(trick.length<4)return{...g,hands,trick,turn:next(seat)};const win=currentWinner(trick,g.trump)!;const t=teamOf(win.seat);const tricksWon=[...g.tricksWon]as[number,number];tricksWon[t]++;const capturedPoints=[...g.capturedPoints]as[number,number];capturedPoints[t]+=trick.reduce((n,p)=>n+cardPoints(p.card,g.trump!),0);if(tricksWon[0]+tricksWon[1]===8){capturedPoints[t]+=10;return finishRound({...g,hands,trick:[],turn:win.seat,tricksWon,capturedPoints})}return{...g,hands,trick:[],turn:win.seat,tricksWon,capturedPoints}}
function finishRound(g:GameState):GameState{const dealerTeam=teamOf(g.dealer);const r=settleRound({cardPoints:g.capturedPoints,declarationPoints:g.declarations,tricks:g.tricksWon,dealerTeam});let A={...g.teams.A},B={...g.teams.B};A.bil+=r.bil[0];B.bil+=r.bil[1];if(r.winner!==null){const losingTeam=(r.winner===0?1:0)as 0|1;if(r.kaput){if(losingTeam===0)A=applyKaputPenalty(A,dealerTeam===0);else B=applyKaputPenalty(B,dealerTeam===1)}else if(dealerTeam===losingTeam){if(losingTeam===0)A=addBolt(A);else B=addBolt(B)}}const target=nextTarget(A.bil,B.bil,g.target);const winner=winnerAtTarget(A.bil,B.bil,g.target);return{...g,phase:winner?"game_over":"round_end",teams:{A,B},target,winner:winner??undefined}}
export function nextRound(g:GameState,random=Math.random):GameState{if(g.phase!=="round_end")throw Error("Round not finished");return startRound(next(g.dealer),g.teams,g.target,random)}
