import{createDeck,shuffleDeck}from"./deck";import{dealFive,DealResult,finishDeal}from"./deal";import{bid,startBidding,Bid,BiddingState}from"./bidding";import{currentWinner,legalCards,PlayedCard}from"./trick";import{cardPoints}from"./cards";import{addBolt,applyKaputPenalty,INITIAL_TARGET,nextTarget,winnerAtTarget}from"./scoring";import{Card,Seat,Suit,TeamId,TeamState}from"./types";import{settleRound}from"./round";import{Declaration,detectDeclarations,noOverlap}from"./declarations";
export type Phase="bidding"|"playing"|"round_end"|"game_over";
export interface GameState{phase:Phase;dealer:Seat;target:number;teams:Record<TeamId,TeamState>;deal:DealResult;bidding:BiddingState;hands?:Record<Seat,Card[]>;initialHands?:Record<Seat,Card[]>;trump?:Suit;turn:Seat;trick:PlayedCard[];tricksWon:[number,number];capturedPoints:[number,number];declarations:[number,number];completedTricks:number;annulledDeclarations:boolean;cancelled:boolean;announced?:Record<Seat,Declaration[]>;bellaDeclared?:Record<Seat,boolean>;winner?:TeamId}
const next=(s:Seat)=>((s+1)%4)as Seat;export const teamOf=(s:Seat):0|1=>s%2===0?0:1;
export function newGame(random=Math.random):GameState{const dealer=Math.floor(random()*4)as Seat;return startRound(dealer,{A:{bil:0,bolts:0},B:{bil:0,bolts:0}},INITIAL_TARGET,random)}
function startRound(dealer:Seat,teams:Record<TeamId,TeamState>,target:number,random=Math.random):GameState{const deal=dealFive(shuffleDeck(createDeck(),random),dealer);return{phase:"bidding",dealer,target,teams,deal,bidding:startBidding(dealer,deal.faceUp.suit),turn:next(dealer),trick:[],tricksWon:[0,0],capturedPoints:[0,0],declarations:[0,0],completedTricks:0,annulledDeclarations:false,cancelled:false}}
export function makeBid(g:GameState,seat:Seat,b:Bid):GameState{if(g.phase!=="bidding")throw Error("Not bidding");const bidding=bid(g.bidding,seat,b);if(!bidding.trump)return{...g,bidding,turn:bidding.turn};const hands=finishDeal(g.deal,g.dealer,bidding.taker!,bidding.trump);const initialHands={0:[...hands[0]],1:[...hands[1]],2:[...hands[2]],3:[...hands[3]]} as Record<Seat,Card[]>;return{...g,phase:"playing",bidding,hands,initialHands,trump:bidding.trump,turn:next(g.dealer),announced:{0:[],1:[],2:[],3:[]},bellaDeclared:{0:false,1:false,2:false,3:false}}}
export function setDeclarationPoints(g:GameState,team:0|1,points:number):GameState{if(g.phase!=="playing")throw Error("Not playing");const declarations=[...g.declarations]as[number,number];declarations[team]=points;return{...g,declarations}}
export function playCard(g:GameState,seat:Seat,card:Card):GameState{if(g.phase!=="playing"||!g.hands||!g.trump)throw Error("Not playing");if(seat!==g.turn)throw Error("Not your turn");const hand=g.hands[seat];const idx=hand.findIndex(c=>c.suit===card.suit&&c.rank===card.rank);if(idx<0)throw Error("Card not in hand");const legal=legalCards(hand,g.trick,g.trump);if(!legal.some(c=>c.suit===card.suit&&c.rank===card.rank))throw Error("Illegal card");const hands={...g.hands,[seat]:hand.filter((_,i)=>i!==idx)};const trick=[...g.trick,{seat,card}];if(trick.length<4)return{...g,hands,trick,turn:next(seat)};const win=currentWinner(trick,g.trump)!;const t=teamOf(win.seat);const tricksWon=[...g.tricksWon]as[number,number];tricksWon[t]++;const capturedPoints=[...g.capturedPoints]as[number,number];capturedPoints[t]+=trick.reduce((n,p)=>n+cardPoints(p.card,g.trump!),0);const completedTricks=g.completedTricks+1;if(tricksWon[0]+tricksWon[1]===8){capturedPoints[t]+=10;return finishRound({...g,hands,trick:[],turn:win.seat,tricksWon,capturedPoints,completedTricks})}return{...g,hands,trick:[],turn:win.seat,tricksWon,capturedPoints,completedTricks}}
function finishRound(g:GameState):GameState{const dealerTeam=teamOf(g.dealer);const r=settleRound({cardPoints:g.capturedPoints,declarationPoints:g.declarations,tricks:g.tricksWon,dealerTeam});let A={...g.teams.A},B={...g.teams.B};A.bil+=r.bil[0];B.bil+=r.bil[1];if(r.winner!==null){const losingTeam=(r.winner===0?1:0)as 0|1;if(r.kaput){if(losingTeam===0)A=applyKaputPenalty(A,dealerTeam===0);else B=applyKaputPenalty(B,dealerTeam===1)}else if(dealerTeam===losingTeam){if(losingTeam===0)A=addBolt(A);else B=addBolt(B)}}const target=nextTarget(A.bil,B.bil,g.target);const winner=winnerAtTarget(A.bil,B.bil,g.target);return{...g,phase:winner?"game_over":"round_end",teams:{A,B},target,winner:winner??undefined}}
export function nextRound(g:GameState,random=Math.random):GameState{if(g.phase!=="round_end")throw Error("Round not finished");return startRound(next(g.dealer),g.teams,g.target,random)}

export function autoAction(g:GameState,seat:Seat):GameState{if(g.turn!==seat)return g;if(g.phase==="bidding"){const allowed=g.bidding.round===1?[g.deal.faceUp.suit]:(["clubs","diamonds","hearts","spades"]as Suit[]).filter(s=>s!==g.deal.faceUp.suit);if(g.bidding.forcedDealer)return makeBid(g,seat,{type:"take",suit:allowed[0]});return makeBid(g,seat,{type:"pass"})}if(g.phase==="playing"&&g.hands&&g.trump){const cards=legalCards(g.hands[seat],g.trick,g.trump);return playCard(g,seat,cards[0])}return g}
export function runBots(g:GameState,human:Seat=0,max=32):GameState{let next=g;let n=0;while(n++<max&&(next.phase==="bidding"||next.phase==="playing")&&next.turn!==human)next=autoAction(next,next.turn);return next}

export function cancelByFourSevens(g:GameState):GameState{if(g.phase!=="playing"||g.completedTricks>2)throw Error("Too late");return{...g,phase:"round_end",cancelled:true}}
export function annulByFourEights(g:GameState):GameState{if(g.phase!=="playing"||g.completedTricks>2)throw Error("Too late");return{...g,annulledDeclarations:true,declarations:[0,0]}}

export function availableForSeat(g:GameState,seat:Seat):Declaration[]{if(g.phase!=="playing"||!g.initialHands||!g.trump)return[];return detectDeclarations(g.initialHands[seat],g.trump).filter(d=>d.kind==="bella"?!g.bellaDeclared?.[seat]:g.completedTricks<=2)}
export function announce(g:GameState,seat:Seat,d:Declaration):GameState{if(g.phase!=="playing"||!g.announced)throw Error("Not playing");if(d.kind==="four7")return cancelByFourSevens(g);if(d.kind==="four8")return annulByFourEights(g);if(d.kind==="bella"){if(g.bellaDeclared?.[seat])throw Error("Bella already declared");const announced={...g.announced,[seat]:[...g.announced[seat],d]};const bellaDeclared={...g.bellaDeclared,[seat]:true} as Record<Seat,boolean>;const declarations=[...g.declarations] as [number,number];declarations[teamOf(seat)]+=20;return{...g,announced,bellaDeclared,declarations}}
 if(g.completedTricks>2)throw Error("Too late");const next=[...g.announced[seat],d];if(!noOverlap(next))throw Error("Overlap");const announced={...g.announced,[seat]:next};const declarations=[...g.declarations] as [number,number];declarations[teamOf(seat)]+=d.points;return{...g,announced,declarations}}
